apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: mateapp
spec:
  containers:
    - name: busybox
      image: niklafinskiy/alpine-curl:1.0.0
      command: ["/bin/sh", "-c", "apk update && apk add coreutils && sleep infinity"]