kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerPort: 6443

# Залишаємо ТІЛЬКИ один вузол. Це критично для HDD та 3GB RAM.
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
  - containerPort: 30080
    hostPort: 30080
