apiVersion: v1
kind: ConfigMap
metadata:
  name: todolist-config
  namespace: todoapp
data:
  PYTHONUNBUFFERED: "1"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  DATABASE_USER: "todolist_user"
  DATABASE_NAME: "todolist_db"