apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: mateapp
spec:
  # ... replicas/strategy/selector/template.metadata.labels як було ...
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: vitalysemeniv/todoapp:3.0.0
          ports:
            - containerPort: 8000    # або 8080, якщо у вас так
          # підключаємо змінні з ConfigMap і Secret
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: PYTHONUNBUFFERED
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: todo-secret
                  key: SECRET_KEY
          # probes/resources залишайте ваші
