apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: mateapp
  labels:
    app: todolist
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/todoapp:3.0.0
        ports:
        - containerPort: 8080
        env:
          - name: EXTERNAL_ENDPOINT
            value: "http://httpbin-api.mateapp.svc.cluster.local"
          - name: PYTHONUNBUFFERED
            valueFrom:
              configMapKeyRef:
                name: todoapp-config
                key: PYTHONUNBUFFERED
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: todoapp-secret
                key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5